
package dk.skat.begrebsmodel._2008._01._01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VirksomhedStamOplysningSamlingHentServicePortType", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VirksomhedStamOplysningSamlingHentServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns dk.skat.begrebsmodel._2008._01._01.VirksomhedStamOplysningSamlingHentO
     */
    @WebMethod
    @WebResult(name = "VirksomhedStamOplysningSamlingHent_O", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/", partName = "Response")
    public VirksomhedStamOplysningSamlingHentO getVirksomhedStamOplysningSamlingHent(
        @WebParam(name = "VirksomhedStamOplysningSamlingHent_I", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/", partName = "Request")
        VirksomhedStamOplysningSamlingHentI request);

    /**
     * 
     * @param request
     * @return
     *     returns dk.skat.begrebsmodel._2008._01._01.KompenserTransSvarType
     */
    @WebMethod
    @WebResult(name = "KompenserTransSvar", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/", partName = "Response")
    public KompenserTransSvarType getKompenserTrans(
        @WebParam(name = "KompenserTrans", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/", partName = "Request")
        KompenserTransType request);

}
