
package dk.skat.begrebsmodel._2008._01._01;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VirksomhedStamOplysningSamlingHentService", targetNamespace = "http://skat.dk/begrebsmodel/2008/01/01/", wsdlLocation = "http://sktudv01esb01:8011/PS_VirksomhedStamOplysningSamlingHent?wsdl")
@HandlerChain(file = "VirksomhedStamOplysningSamlingHentService_handler.xml")
public class VirksomhedStamOplysningSamlingHentService
    extends Service
{

    private final static URL VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_EXCEPTION;
    private final static QName VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_QNAME = new QName("http://skat.dk/begrebsmodel/2008/01/01/", "VirksomhedStamOplysningSamlingHentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sktudv01esb01:8011/PS_VirksomhedStamOplysningSamlingHent?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_WSDL_LOCATION = url;
        VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_EXCEPTION = e;
    }

    public VirksomhedStamOplysningSamlingHentService() {
        super(__getWsdlLocation(), VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_QNAME);
    }

    public VirksomhedStamOplysningSamlingHentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_QNAME, features);
    }

    public VirksomhedStamOplysningSamlingHentService(URL wsdlLocation) {
        super(wsdlLocation, VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_QNAME);
    }

    public VirksomhedStamOplysningSamlingHentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_QNAME, features);
    }

    public VirksomhedStamOplysningSamlingHentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VirksomhedStamOplysningSamlingHentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VirksomhedStamOplysningSamlingHentServicePortType
     */
    @WebEndpoint(name = "VirksomhedStamOplysningSamlingHentPort")
    public VirksomhedStamOplysningSamlingHentServicePortType getVirksomhedStamOplysningSamlingHentPort() {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2008/01/01/", "VirksomhedStamOplysningSamlingHentPort"), VirksomhedStamOplysningSamlingHentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VirksomhedStamOplysningSamlingHentServicePortType
     */
    @WebEndpoint(name = "VirksomhedStamOplysningSamlingHentPort")
    public VirksomhedStamOplysningSamlingHentServicePortType getVirksomhedStamOplysningSamlingHentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2008/01/01/", "VirksomhedStamOplysningSamlingHentPort"), VirksomhedStamOplysningSamlingHentServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_EXCEPTION!= null) {
            throw VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_EXCEPTION;
        }
        return VIRKSOMHEDSTAMOPLYSNINGSAMLINGHENTSERVICE_WSDL_LOCATION;
    }

}
