
package dk.skat.begrebsmodel._2009._01._15;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistreringForholdBevillingHentService", targetNamespace = "http://skat.dk/begrebsmodel/2009/01/15/", wsdlLocation = "http://sktudv01esb01:8011//PS_RegistreringForholdBevillingHentService?wsdl")
public class RegistreringForholdBevillingHentService
    extends Service
{

    private final static URL REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_EXCEPTION;
    private final static QName REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_QNAME = new QName("http://skat.dk/begrebsmodel/2009/01/15/", "RegistreringForholdBevillingHentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://sktudv01esb01:8011//PS_RegistreringForholdBevillingHentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_WSDL_LOCATION = url;
        REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_EXCEPTION = e;
    }

    public RegistreringForholdBevillingHentService() {
        super(__getWsdlLocation(), REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_QNAME);
    }

    public RegistreringForholdBevillingHentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_QNAME, features);
    }

    public RegistreringForholdBevillingHentService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_QNAME);
    }

    public RegistreringForholdBevillingHentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_QNAME, features);
    }

    public RegistreringForholdBevillingHentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistreringForholdBevillingHentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistreringForholdBevillingHentServicePortType
     */
    @WebEndpoint(name = "RegistreringForholdBevillingHentPort")
    public RegistreringForholdBevillingHentServicePortType getRegistreringForholdBevillingHentPort() {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "RegistreringForholdBevillingHentPort"), RegistreringForholdBevillingHentServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistreringForholdBevillingHentServicePortType
     */
    @WebEndpoint(name = "RegistreringForholdBevillingHentPort")
    public RegistreringForholdBevillingHentServicePortType getRegistreringForholdBevillingHentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://skat.dk/begrebsmodel/2009/01/15/", "RegistreringForholdBevillingHentPort"), RegistreringForholdBevillingHentServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_EXCEPTION!= null) {
            throw REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_EXCEPTION;
        }
        return REGISTRERINGFORHOLDBEVILLINGHENTSERVICE_WSDL_LOCATION;
    }

}
