//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 04:04:11 PM IST 
//


package dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdvisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdvisType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}AdvisNummer" minOccurs="0"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}AdvisTekst"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}ServiceID" minOccurs="0"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}Identifikation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdvisType", propOrder = {
    "advisNummer",
    "advisTekst",
    "serviceID",
    "identifikation"
})
public class AdvisType {

    @XmlElement(name = "AdvisNummer")
    protected BigInteger advisNummer;
    @XmlElement(name = "AdvisTekst", required = true)
    protected String advisTekst;
    @XmlElement(name = "ServiceID")
    protected String serviceID;
    @XmlElement(name = "Identifikation")
    protected Identifikation identifikation;

    /**
     * Gets the value of the advisNummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAdvisNummer() {
        return advisNummer;
    }

    /**
     * Sets the value of the advisNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAdvisNummer(BigInteger value) {
        this.advisNummer = value;
    }

    /**
     * Gets the value of the advisTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdvisTekst() {
        return advisTekst;
    }

    /**
     * Sets the value of the advisTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdvisTekst(String value) {
        this.advisTekst = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the identifikation property.
     * 
     * @return
     *     possible object is
     *     {@link Identifikation }
     *     
     */
    public Identifikation getIdentifikation() {
        return identifikation;
    }

    /**
     * Sets the value of the identifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifikation }
     *     
     */
    public void setIdentifikation(Identifikation value) {
        this.identifikation = value;
    }

}
