//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 04:04:11 PM IST 
//


package dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FejlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FejlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}FejlNummer" minOccurs="0"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}FejlTekst"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}ServiceID" minOccurs="0"/>
 *         &lt;element ref="{http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/}Identifikation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FejlType", propOrder = {
    "fejlNummer",
    "fejlTekst",
    "serviceID",
    "identifikation"
})
public class FejlType {

    @XmlElement(name = "FejlNummer")
    protected BigInteger fejlNummer;
    @XmlElement(name = "FejlTekst", required = true)
    protected String fejlTekst;
    @XmlElement(name = "ServiceID")
    protected String serviceID;
    @XmlElement(name = "Identifikation")
    protected Identifikation identifikation;

    /**
     * Gets the value of the fejlNummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFejlNummer() {
        return fejlNummer;
    }

    /**
     * Sets the value of the fejlNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFejlNummer(BigInteger value) {
        this.fejlNummer = value;
    }

    /**
     * Gets the value of the fejlTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFejlTekst() {
        return fejlTekst;
    }

    /**
     * Sets the value of the fejlTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFejlTekst(String value) {
        this.fejlTekst = value;
    }

    /**
     * Gets the value of the serviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceID() {
        return serviceID;
    }

    /**
     * Sets the value of the serviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceID(String value) {
        this.serviceID = value;
    }

    /**
     * Gets the value of the identifikation property.
     * 
     * @return
     *     possible object is
     *     {@link Identifikation }
     *     
     */
    public Identifikation getIdentifikation() {
        return identifikation;
    }

    /**
     * Sets the value of the identifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifikation }
     *     
     */
    public void setIdentifikation(Identifikation value) {
        this.identifikation = value;
    }

}
