//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 04:04:11 PM IST 
//


package dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactoryTransaktions {

    private final static QName _FejlNummer_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "FejlNummer");
    private final static QName _TransaktionsID_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "TransaktionsID");
    private final static QName _FejlTekst_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "FejlTekst");
    private final static QName _Fejl_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "Fejl");
    private final static QName _AdvisNummer_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "AdvisNummer");
    private final static QName _ServiceID_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "ServiceID");
    private final static QName _Advis_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "Advis");
    private final static QName _TransaktionsTid_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "TransaktionsTid");
    private final static QName _HovedOplysningerSvar_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "HovedOplysningerSvar");
    private final static QName _AdvisTekst_QNAME = new QName("http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", "AdvisTekst");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31
     * 
     */
    public ObjectFactoryTransaktions() {
    }

    /**
     * Create an instance of {@link FejlType }
     * 
     */
    public FejlType createFejlType() {
        return new FejlType();
    }

    /**
     * Create an instance of {@link HovedOplysningerSvarType }
     * 
     */
    public HovedOplysningerSvarType createHovedOplysningerSvarType() {
        return new HovedOplysningerSvarType();
    }

    /**
     * Create an instance of {@link Identifikation }
     * 
     */
    public Identifikation createIdentifikation() {
        return new Identifikation();
    }

    /**
     * Create an instance of {@link AdvisType }
     * 
     */
    public AdvisType createAdvisType() {
        return new AdvisType();
    }

    /**
     * Create an instance of {@link SvarReaktionType }
     * 
     */
    public SvarReaktionType createSvarReaktionType() {
        return new SvarReaktionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "FejlNummer")
    public JAXBElement<BigInteger> createFejlNummer(BigInteger value) {
        return new JAXBElement<BigInteger>(_FejlNummer_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "TransaktionsID")
    public JAXBElement<String> createTransaktionsID(String value) {
        return new JAXBElement<String>(_TransaktionsID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "FejlTekst")
    public JAXBElement<String> createFejlTekst(String value) {
        return new JAXBElement<String>(_FejlTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FejlType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "Fejl")
    public JAXBElement<FejlType> createFejl(FejlType value) {
        return new JAXBElement<FejlType>(_Fejl_QNAME, FejlType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "AdvisNummer")
    public JAXBElement<BigInteger> createAdvisNummer(BigInteger value) {
        return new JAXBElement<BigInteger>(_AdvisNummer_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "ServiceID")
    public JAXBElement<String> createServiceID(String value) {
        return new JAXBElement<String>(_ServiceID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdvisType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "Advis")
    public JAXBElement<AdvisType> createAdvis(AdvisType value) {
        return new JAXBElement<AdvisType>(_Advis_QNAME, AdvisType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "TransaktionsTid")
    public JAXBElement<XMLGregorianCalendar> createTransaktionsTid(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TransaktionsTid_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HovedOplysningerSvarType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "HovedOplysningerSvar")
    public JAXBElement<HovedOplysningerSvarType> createHovedOplysningerSvar(HovedOplysningerSvarType value) {
        return new JAXBElement<HovedOplysningerSvarType>(_HovedOplysningerSvar_QNAME, HovedOplysningerSvarType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", name = "AdvisTekst")
    public JAXBElement<String> createAdvisTekst(String value) {
        return new JAXBElement<String>(_AdvisTekst_QNAME, String.class, null, value);
    }

}
