//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.18 at 04:04:11 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://skat.dk/begrebsmodel/xml/schemas/kontekst/2007/05/31/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.skat.begrebsmodel.xml.schemas.kontekst._2007._05._31;
